### PR TITLE
Facebook graph api versioning 

### PR DESCRIPTION
**Pull request by kalilou**
In this pull request I've created separate files for the exceptions and the urls which are imported in the facebook_utils file if needed. 

But still the major change is all about taking into the facebook graph api versioning.

### CODE REVIEW

**Comment by kalilou** [comment]
By the way, I will add the docstring which I have removed when I started working on the files

**Comment by jvanasco** [comment]
wow this looks great.  i'll dive in this weekend.

if you're going to keep working on this, it might make best sense to do additional work in a "feature branch" instead of "master".

**Comment by vanng822** [comment]
Look like the license have been removed. Maybe put it in a LICENSE file?

**Comment by jvanasco** [comment]
I ticked the missing license as https://github.com/jvanasco/facebook_utils/issues/3

It should be BSD, which was the original intent and the pypi classifier.  MIT was listed in the setup.py several releases later, with BSD in there too, so I'll keep it as that.

**Comment by jvanasco** [comment]
I'll probably have a .30 release based on this today.

It had a lot of errors that needed fixing and bunch of tests.

**Comment by jvanasco** [comment]
This is all merged in.   Thanks for the work.

There is one possible incompatibility with your codebase.  Facebook is non-standard in how they use 'app' and 'client'.  All the docs say `app_*`, all the endpoints expect `client_*`.

In order to better resonate with the facebook docs, I standardized everything to use `app_id` and `app_secret` internally -- but use `client_*` when talking to the endpoint.

**Comment by kalilou** [comment]
Hi jvanasco,

Sorry the silence, I have been sick lately, just got back to work today.  Since facebook kinda dropped the python support for the API, I will working on improving it. 

Great work for wrapping all together, this is awesome. I was bit in hurry to apply the versioning of the graph api for our codebase.

**Comment by jvanasco** [comment]
You should make sure to run flake8 in the future.  It finds most errors before you realize they exist.

**Comment by kalilou** [comment]
Awesome, I actually started using it on a daily basis at work. Coool stuff

**Pull request merged**
